### ISSUE TITLE
jcenter shutting down

### ISSUE THREAD

**Issue by jbunting** [unbroken-dome/jackson-bean-validation#6]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Given this announcement it looks like we're no longer going to be able to access the library via jcenter.

**Comment by jbunting** [comment]
For what it's worth, not trying to rush anything - I know it's a pretty fresh announcement. In evaluating my team's codebase for dependencies hosted on jcenter, this is one that came up so we're just trying to get out in front of it to avoid scrambling. 

I'd be happy to assist with migration.

**Comment by tkrullmann** [comment]
Done. 0.6.0 is available on Maven Central now
